networks:
  backend:

services:
  ticket-booking:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/$POSTGRES_DB
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - backend
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s